<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="yinons-MacBook-Pro.local" failures="0" tests="5" name="Tests.SignUpByFacbookTest" time="69.595" errors="1" timestamp="18 Jan 2018 15:17:08 GMT" skipped="0">
  <testcase classname="Tests.SignUpByFacbookTest" name="LoginWithFacbookWrongUserName" time="14.844"/>
  <testcase classname="Tests.SignUpByFacbookTest" name="LoginWithFacbookWrongPassword" time="9.987"/>
  <testcase classname="Tests.SignUpByFacbookTest" name="LoginWithFacbookWithoutPassword" time="7.948"/>
  <testcase classname="Tests.SignUpByFacbookTest" name="LoginWithFacbookWithoutUser" time="3.352">
    <error message="An unknown server-side error occurred while processing the command. Original error: Error while executing atom: Element is no longer attached to the DOM (status: 10) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
Build info: version: &#039;3.8.1&#039;, revision: &#039;6e95a6684b&#039;, time: &#039;2017-12-01T19:05:32.194Z&#039;
System info: host: &#039;yinons-MacBook-Pro.local&#039;, ip: &#039;fe80:0:0:0:d7:ef92:39a:15ea%en0&#039;, os.name: &#039;Mac OS X&#039;, os.arch: &#039;x86_64&#039;, os.version: &#039;10.12.6&#039;, java.version: &#039;9.0.1&#039;
Driver info: io.appium.java_client.ios.IOSDriver
Capabilities {app: /Users/yinonwishi/Desktop/W..., automationName: XCuiTest, browserName: , databaseEnabled: false, deviceName: iPhone X, javascriptEnabled: true, locationContextEnabled: false, networkConnectionEnabled: false, newCommandTimeout: 5000, platform: MAC, platformName: MAC, platformVersion: 11.1, startIWDP: true, takesScreenshot: true, udid: 239532F5-4C8E-4067-B5A3-914..., webStorageEnabled: false}
Session ID: a287c7cd-fa3a-457d-af58-941d708ce094" type="org.openqa.selenium.WebDriverException">
      <![CDATA[org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Error while executing atom: Element is no longer attached to the DOM (status: 10) (WARNING: The server did not provide any stacktrace information)Command duration or timeout: 0 millisecondsBuild info: version: '3.8.1', revision: '6e95a6684b', time: '2017-12-01T19:05:32.194Z'System info: host: 'yinons-MacBook-Pro.local', ip: 'fe80:0:0:0:d7:ef92:39a:15ea%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.6', java.version: '9.0.1'Driver info: io.appium.java_client.ios.IOSDriverCapabilities {app: /Users/yinonwishi/Desktop/W..., automationName: XCuiTest, browserName: , databaseEnabled: false, deviceName: iPhone X, javascriptEnabled: true, locationContextEnabled: false, networkConnectionEnabled: false, newCommandTimeout: 5000, platform: MAC, platformName: MAC, platformVersion: 11.1, startIWDP: true, takesScreenshot: true, udid: 239532F5-4C8E-4067-B5A3-914..., webStorageEnabled: false}Session ID: a287c7cd-fa3a-457d-af58-941d708ce094at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)at org.openqa.selenium.remote.http.JsonHttpResponseCodec.reconstructValue(JsonHttpResponseCodec.java:40)at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:80)at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:44)at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:164)at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:89)at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)at io.appium.java_client.ios.IOSDriver.execute(IOSDriver.java:1)at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:279)at io.appium.java_client.DefaultGenericMobileElement.execute(DefaultGenericMobileElement.java:45)at io.appium.java_client.MobileElement.execute(MobileElement.java:1)at io.appium.java_client.ios.IOSElement.execute(IOSElement.java:1)at org.openqa.selenium.remote.RemoteWebElement.isEnabled(RemoteWebElement.java:150)at PageObjects.BasePage.ElementEnable(BasePage.java:76)at PageObjects.FacbookPage.LoginWithFacbookWithoutUser(FacbookPage.java:71)at Tests.SignUpByFacbookTest.LoginWithFacbookWithoutUser(SignUpByFacbookTest.java:26)at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.base/java.lang.reflect.Method.invoke(Method.java:564)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
    </error>
  </testcase> <!-- LoginWithFacbookWithoutUser -->
  <testcase classname="Tests.SignUpByFacbookTest" name="DoLoginWithFacbook" time="33.464"/>
</testsuite> <!-- Tests.SignUpByFacbookTest -->
